projectacrn/acrn-devicemodel

Makefile

The demos scripts are not installed when "make install" is invoked.
This patch adds a rule to copy them to /usr/share/acrn
Signed-off-by: Miguel Bernal Marin <miguel.bernal.marin@linux.intel.com>

makefile: install the demo scripts

---

hw/pci/core.c

Writing PCIR_BIOS is to get PCI ROM resource length. Ingore the request
as it's not support currently. Else, guest might get wrong information
about the PCI ROM resource.
Signed-off-by: Shuo Liu <shuo.a.liu@intel.com>

Ignore length of resource for PCI ROM request

---

core/main.c

It will be easier if we want to add more command line options
with long options.

dm: use getopt_long instead of getopt to parse dm cmdline

---

core/vmmapi.c
include/vmmapi.h

Also save the uuid to ctx in case DM needs to access the
uuid.

vm: Pass uuid from DM commandline to vm as GUID.

---

samples/launch_uos.sh

Documentation says to use CL version 21260, but sample script wasn't
updated.
Signed-off-by: David B. Kinder <david.b.kinder@intel.com>

update launch_uos.sh script

---

hw/pci/passthrough.c

IPU devices are using I2C device with physical BDF 0:16.0.
The I2C controller has the dependency on ACPI info.
This patch is to add ACPI info for the I2C controller and the two IPU
devices that are under the scope of I2C.
Note:
This patch is specific for GP platform.
Signed-off-by: Shiqing Gao <shiqing.gao@intel.com>

dm: add ACPI info for ipu pass-through

---

Makefile
core/main.c
core/sw_load_bzimage.c
core/sw_load_common.c
include/sw_load.h
include/vmmapi.h

The common loader code is put to sw_load_common.c
The loader code for directly kernel loading is put to sw_load_bzimage.c
The further change for SBL will be put to sw_load_sbl.c

DM: split sw_load.c to sw_load.c and sw_load_direct.c

---

hw/acpi/acpi.c

gcc8 showed following errors when build DM:
error: argument to ‘sizeof’ in ‘strncpy’ call is the same
expression as the source; did you mean to use the size of the
destination? [-Werror=sizeof-pointer-memaccess]
It looks like wrong parameter was given to strncpy.
Acked-by: Anthony Xu <anthony.xu@intel.com>

DM: fix build error with gcc-8.

---

core/main.c
core/sw_load_vsbl.c
core/vmmapi.c
include/dm.h

The trusty enabled or not will be passed to HV
with create vm hypercall. It's passed to vSBL within
config page also.
Acked-by: Anthony Xu <anthony.xu@intel.com>

DM: Add long option to enable trusty

---

hw/pci/core.c
include/pci_core.h

pci_emul_add_capability is needed by virtio 1.0 framework to add
pci vendor capability from outside of pci core.
Signed-off-by: Jian Jun Chen <jian.jun.chen@intel.com>
Reviewed-by: Hao Li <hao.l.li@intel.com>

dm: export pci_emul_add_capability

---

hw/pci/virtio/virtio.c
include/virtio.h

This patchset implemented the virtio 1.0 framework based on virtio spec
v1.0 cs4.
Currently only modern feature negotiation has been verified to be working
with virtio 1.0 support. New VBS-U, e.g. virtio-input, based on virtio 1.0
specification will be developed to verify the correctness of virtio 1.0
framework.
Two PCI bars are used in virtio 0.9.5 (referred as virtio legacy). One is
for PIO, the other is for MSIX. Both the virtio common configuration
registers and device-specific configuration registers are placed in the
PIO bar together.
In virtio 1.0 (referred as virtio modern) 5 PCI capabilities are added to
the PCI configuration space of the virtio PCI device.
- Common configuration capability
- Notification capability
- ISR capability
- Device-specific configuration capability
- …

Virtio 1.0 framework

---

.travis-dockerfiles/Dockerfile.centos7
.travis-dockerfiles/Dockerfile.clearlinux
.travis-dockerfiles/Dockerfile.debian8
.travis-dockerfiles/Dockerfile.fedora26
.travis-dockerfiles/Dockerfile.fedora27
.travis-dockerfiles/Dockerfile.ubuntu14.04
.travis-dockerfiles/Dockerfile.ubuntu16.04
.travis-dockerfiles/README.md
.travis.yml

Enable Travis CI testing for the following development host OSs:
* Clearlinux
* Ubuntu 16.04
* Fedora 26
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

Enable Travis CI testing

---

Makefile
core/vmmapi.c
hw/acpi/acpi.c
hw/acpi/acpi_pm.c
include/acpi.h
include/public/acrn_common.h
include/public/vhm_ioctl_defs.h
include/vmmapi.h

The patch set would generate ACPI P-state objects(i.e. _PCT/_PPC/_PSS) ASL
for DSDT, to make UOS be capable of controling its P-state.
HV is responsible for constructing Px data and provide hypercall for VHM
to query, then DM will get these data through kernel VHM service and build
the DSDT for UOS.
With this patch set, UOS CPU should have P-state working if acpi-cpufreq
driver is enabled in UOS kernel.
change log:
v4: (1) px data should be per-cpu of target vm, but v3 did not
specify the target vm and vcpu so just get the vcpu px data
of vm0, fixed it to specific vm and vcpu;
(2) add vmctx as parameter of write acpi table function pointer,
so we can pass vmid to write dsdt function;
(3) do not need store px data before build acpi table, just
get the px data when building dsdt table;
(4) …

DM: Build UOS ACPI DSDT with Px data

---

hw/pci/ahci.c
include/pci_core.h

A couple of problems appeared on Ubuntu 14.04 (gcc 4.8.4) when we
turned on additional compiler flags with commit
519c4285cf104a594776591075ee1c6ee4d61815a. This patch fixes these
problems by adhering to the strict anti-aliasing rules and also
initializing the 'tfd' variable where the compile believed it
_could_ be used uninitialized.
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

Fix compilation on Ubuntu 14.04

---

.travis-dockerfiles/Dockerfile.fedora26
.travis-dockerfiles/Dockerfile.fedora27

The 'find' command was not installed in our minimal Fedora 26
and 27-based Docker images. This resulted in a non-fatal error
when performing a 'make clean'. This commit adds this utility
(available in the 'findutils' package).
Signed-off-by: Geoffroy Van Cutsem <geoffroy.vancutsem@intel.com>

Add 'findutils' to Fedora-based Docker images

---

Makefile
hw/pci/virtio/virtio_heci.c
include/heci.h

This implement HECI virtualization PV backend service based on virtio
userspace framework. This service introduce a virtio-heci device model
for DM, and can be enabled by DM parameter '-s [BUS NO],virtio-heci'.
The HECI virtualization need both backend service in device-model and
frontend driver in guest to work. Back-end service mainly emulate HECI 
device's behaviors to satisfy frontend driver. They are based on virtio
userspace framework. Currently, it is using two virtqueues, one is for
TX and another is for RX. There are also two threads for TX and RX in
current implementation.
Now, all MEI clients will be exposed by default. Backend service will 
has a HBM type client emulator to process HECI Bus Message from guest.
Other all client will be treated as NORMAL type clients by now. …

Backend service for HECI virtualization

---

hw/platform/rtc.c

Signed-off-by: Liu Shuo <shuo.a.liu@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

DM: use standard offsetof to avoid duplicate definition

---

hw/pci/ahci.c
include/pci_core.h

This reverts commit bc0579d0ffba6a1b0d1abe55a0af03d935b959f0.
The commit bc0579d makes acrn-dm crashed when launch UOS.
Crash log:
./launch_UOS.sh: line 112:   377 Segmentation fault (core dumped) acrn-dm ...
dmesg log:
acrn-dm[1264]: segfault at 1f0 ip 0000000000412257 sp 00007fffc1af9920 error 6 in acrn-dm[400000+3d000]
After this patch reverted, UOS launched successfully.

Revert "Fix compilation on Ubuntu 14.04"

---

Makefile
hw/pci/ahci.c

There are two build issues:
- add -fno-strict-aliasing to address
error: dereferencing type-punned pointer will break strict-aliasing rules
- initialize tfd to zero to address
error: ‘tfd’ may be used uninitialized in this function

DM: fix build issue with gcc 4.8.4 on ubuntu 14.04

---

hw/pci/virtio/virtio_console.c

If multiple ports are defined in the command line, is_console is
not set to a correct value for non-console ports when the definition
of this non-console port is following the definition of a console port.
For example in below definition, the second port is configured as
console port which is not correct:
-s 5,virtio-console,@pty:pty_port,file:file_port=/home/root/test1
Signed-off-by: Jian Jun Chen <jian.jun.chen@intel.com>
Reviewed-by: Zhao Yakui <yakui.zhao@intel.com>
Acked-by: Anthony Xu <anthony.xu@intel.com>

dm: virtio-console: Fix the bug that ports cannot work

---

hw/pci/wdt_i6300esb.c

to avoid system resource/memory leaked when guest os reboot.
Signed-off-by: Minggui Cao <minggui.cao@intel.com>

delete watchdog timer when deinit is called

---

hw/pci/passthrough.c

Adds ACPI tables for 0:18.0(UART) device
Signed-off-by: Edwin Zhai <edwin.zhai@intel.com>
Reviewed-by: Zhao Yakui <yakui.zhao@intel.com>
Reviewed-by: Kevin Tian <kevin.tian@intel.com>

VTd: bluetooth passthrough support

---

hw/platform/ioc.c

Add AmbientTemperature signal into the whitelist,
instead of TemperatureSensorEnvironment signal.
Signed-off-by: Liu Yuan <yuan1.liu@intel.com>
Reviewed-by: Wang Yu <yu1.wang@intel.com>

IOC mediator: update signal whitelist

---

hw/pci/virtio/virtio_net.c

If guest doesn't initialize the net device, the tx thread will
block at the first tx_cond wait. When virtio_net_tx_stop is
invoked, the tx_thread will block on second tx_cond then.
Check whether we should exit tx_thread after first tx_cond
waiting
Reviewed-by: Hao Li <hao.l.li@intel.com>

DM: fix virtio_net tx_thread block issue

---

tools/acrn-manager/acrnctl.c

The launch script can output log messages, that should be text.
But it is not always true. E.g. "launch_UOS.sh -U 2" echo message
contain '\0', The 'grep' command will show "Binary file (xxxxxx)
matches", thus acrnctl can't get the vmname. We can use 'grep -a'
instead.
Acked-by: Xu Anthony <anthony.xu@intel.com>
Reviewed-by: Yan Like <like.yan@intel.com>
Reported-by: Chen ChengX <chengx.chen@intel.com>
Signed-off-by: Tao Yuhong <yuhong.tao@intel.com>

Bugfix: DM:tools:acrnctl launch script output is binary file

---

core/sw_load_bzimage.c

Print an error message and exit rather than using assert, so it is
more obvious what the problem is and no core files are produced.
Fixes #61
Signed-off-by: Icarus Sparry <icarus.w.sparry@intel.com>

Use exit instead of assert when checking images

---

hw/acpi/acpi_pm.c
include/public/acrn_common.h

The patch set would generate ACPI C-state objects(i.e. _CST) ASL for DSDT,
to make UOS be capable of controling its C-state.
HV is responsible for constructing Cx data and provide hypercall for VHM
to query, then DM will get these data through kernel VHM service and build
the DSDT for UOS.
With this patch set, UOS CPU should have C-state working if acpi-idle
driver is enabled in UOS kernel.

Build UOS ACPI DSDT with Cx data

---

Makefile
hw/pci/virtio/virtio_input.c
include/virtio.h

This patchset implemented virtio-input backend driver in acrn device
model based on virtio 1.0 framework.
Properties of host input device are read from evdev character device
driver to service configuration request from FE driver during the device
specific configuration negotiation. The properties include:
- name and devids
- propbit and evbit
- absbit
Input events are polled via mevent and are read from evdev character
device driver when available. A local event queue is implemented to
cache input events utill a SYN event is read. All cached input events
are then sent to guest via virtqueue.
v4 --> v5:
- rename VIRTIO_INPUT_EVENT to VIRTIO_INPUT_EVENT_QUEUE
- rename VIRTIO_INPUT_STATUS to VIRTIO_INPUT_STATUS_QUEUE
- rename INPUT_PACKET_SIZE to VIRTIO_INPUT_PACKET_SIZE
- add description …

Virtio input

---

hw/pci/core.c

The original code assume there is only one configuration for
virtio-blk, and 'b' is just located after that configuration,
so to get the value of 'b', it will end char *config by adding
'\0' after the first configuration.
Thus, char *config will change from:
/XXXX_vdisk_file,range=xxx/xxx
to:
/XXXX_vdisk_file
and char *b will point to:
range=xxx/xxx
So, the range will never take effect for virtio-blk.
Now, 'b' is designed to located just after emul, and
char *config will point to all configurations after 'b'.
Note: only ",b," is taken for boot device option.
Signed-off-by: Conghui Chen <conghui.chen@intel.com>
Reviewed-by: Yin Fengwei <fengwei.yin@intel.com>
Reviewed-by: Hao Li <hao.l.li@intel.com>

DM: move boot device option 'b' just after emul

---

core/main.c

With curren code, DM will ignore the SIGHUP signal generated from
SOS reboot that causes DM will not release resource when SOS reboot
occurs.
Signed-off-by: Zheng, Gen <gen.zheng@intel.com>
Reviewed-by: Jason Chen CJ <jason.cj.chen@intel.com>

DM: bug fix in handling signal

---

hw/acpi/acpi_pm.c
include/public/acrn_common.h

The name of acrn_register is too generic, rename to acpi_generic_address
which is more common.
Signed-off-by: Victor Sun <victor.sun@intel.com>
Acked-by: Kevin Tian <kevin.tian@intel.com>

DM: rename acrn_register to acpi_generic_address
